language: julia

julia:
    - 1.0
    - 1.1
    - nightly

os:
    - linux

matrix:
    allow_failures:
        - julia: nightly

notifications:
    email: false
 
after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("SailRoute")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

